### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by sfyang2** [suterma/vue-peaks#2]
1.使用file://xxx.mp3的本地链接，无法工作
2.参考demo示例，无法工作，具体代码和错误信息截图如下：
代码：
<img width="791" alt="image" src="https://user-images.githubusercontent.com/46621212/224084372-295bb0d3-62eb-44ff-a52d-41c1405ffb5a.png">
<img width="583" alt="image" src="https://user-images.githubusercontent.com/46621212/224084435-08a0cecd-28e1-409b-a559-6df7698351a9.png">
错误信息：
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/46621212/224084870-29b72323-9e8d-431b-99be-4b6b8c1551e1.png">
<img width="1651" alt="image" src="https://user-images.githubusercontent.com/46621212/224084872-8b8cccbe-7af4-44a0-8520-5fdcbc68f4cc.png">

**Comment by suterma** [comment]
Hi, the error you got suggests that there might be a conflict in vue. Can you check whether this problem applies and the solution helps?: https://github.com/vuejs/core/issues/4344#issuecomment-912627569

**Comment by suterma** [comment]
I could not reproduce, mostly because of me not being able to understand chinese.
