### ISSUE TITLE
Is possible to use with .dat files ?

### ISSUE THREAD

**Issue by balbinott** [suterma/vue-peaks#3]
Hello, i was wondering if i can use this component loading .dat files to peaks.js?

**Comment by suterma** [comment]
Yes, it should work, by using the options with the `AudioPeaks` component. See the [available properties](https://suterma.github.io/vue-peaks/#available-properties) from the demo page. 

You can use all [`peaks.js` options](https://suterma.github.io/vue-peaks/#using-options), except those specifically mentioned. Although I never tried, [.dat files should work like described by the original peaks.js documentation](https://github.com/bbc/peaks.js#pre-computed-waveform-data).

May I ask you to report back whether it worked for you?

**Comment by davthedev** [comment]
I am using prerendered .dat files and it works.
Use `dataUri.arraybuffer` key in the `peaksOptions` to pass the URL if the .dat file should be downloaded.

**Comment by suterma** [comment]
Thanks @davthedev for reporting. I am closing this issue now.
